# Generated by Django 6.0.6 on 2026-06-25 05:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_initial'),
        ('submissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='source_code',
            new_name='code',
        ),
        migrations.AddField(
            model_name='submission',
            name='passed_cases',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submission',
            name='result',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='total_cases',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='submission',
            name='language',
            field=models.CharField(default='python', max_length=20),
        ),
        migrations.AlterField(
            model_name='submission',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.question'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
