# Generated by Django 6.0.6 on 2026-06-30 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_alter_testcase_input_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.TextField(blank=True, help_text='Reference solution shown after 3 failed attempts'),
        ),
        migrations.AddField(
            model_name='question',
            name='hint',
            field=models.TextField(blank=True, help_text='Hint shown to candidates'),
        ),
    ]
