# Generated by Django 6.0.6 on 2026-07-01 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_question_answer_question_hint'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='time_limit',
            field=models.PositiveIntegerField(default=60, help_text='Time limit in minutes for this question'),
        ),
    ]
