# Generated by Django 6.0.6 on 2026-07-04 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_question_time_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('python', 'Python3'), ('javascript', 'JavaScript'), ('java', 'Java'), ('cpp', 'C++'), ('c', 'C'), ('csharp', 'C#'), ('go', 'Go'), ('kotlin', 'Kotlin'), ('swift', 'Swift'), ('rust', 'Rust'), ('ruby', 'Ruby'), ('php', 'PHP'), ('dart', 'Dart'), ('scala', 'Scala'), ('typescript', 'TypeScript')], max_length=20)),
                ('starter_code', models.TextField(blank=True, help_text='Boilerplate code pre-filled in the editor when this language is selected. Leave blank to use the default template.')),
                ('hint', models.TextField(blank=True, help_text='Hint shown to candidates when this language is selected')),
                ('answer', models.TextField(blank=True, help_text='Reference solution shown after 3 failed attempts, for this language')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_contents', to='questions.question')),
            ],
            options={
                'ordering': ['language'],
                'unique_together': {('question', 'language')},
            },
        ),
    ]
