# Generated by Django 6.0.6 on 2026-07-06 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_question_time_limit'),
        ('questions', '0007_seed_basic_questions'),
    ]

    operations = [
    ]
