# Generated by Django 4.2.7 on 2026-07-06 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_question_time_limit'),
        ('questions', '0007_seed_basic_questions'),
    ]

    operations = [
    ]
