# Generated by Django 4.2.7 on 2026-07-07 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_merge_20260706_1151'),
        ('questions', '0008_merge_20260706_1232'),
    ]

    operations = [
    ]
