# Generated by Django 6.0.6 on 2026-07-08 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_questionlanguage'),
        ('questions', '0009_merge_20260707_1505'),
    ]

    operations = [
    ]
