# Generated by Django 6.0.6 on 2026-07-08 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_question_contest_fields'),
        ('questions', '0009_merge_20260707_1505'),
    ]

    operations = [
    ]
