# Generated by Django 5.2.15 on 2026-07-10 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0010_merge_0007_questionlanguage_0009_merge_20260707_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionlanguage',
            name='language',
            field=models.CharField(choices=[('python', 'Python3'), ('java', 'Java'), ('javascript', 'JavaScript'), ('c', 'C'), ('cpp', 'C++'), ('ruby', 'Ruby')], max_length=20),
        ),
    ]
