# Generated by Django 6.0.6 on 2026-07-06 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_assessment_is_active_question_time_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='marks',
            field=models.IntegerField(default=10),
        ),
    ]
