# Generated by Django 5.2.15 on 2026-07-07 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_question_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='time_limit',
            field=models.PositiveIntegerField(default=60, help_text='Time limit in minutes for this question'),
        ),
    ]
