# Generated by Django 6.0.6 on 2026-07-08 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_question_time_limit'),
        ('assessments', '0003_question_marks'),
    ]

    operations = [
    ]
