# Generated by Django 6.0.6 on 2026-07-08 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_question_marks'),
        ('assessments', '0003_question_time_limit'),
    ]

    operations = [
    ]
