# Generated by Django 6.0.6 on 2026-07-08 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_merge_0003_question_marks_0003_question_time_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='marks',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
