# Generated by Django 6.0.6 on 2026-07-04 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True)),
                ('contest_notifications', models.BooleanField(default=True)),
                ('course_update_notifications', models.BooleanField(default=True)),
                ('submission_result_notifications', models.BooleanField(default=True)),
                ('team_member_notifications', models.BooleanField(default=True)),
                ('spam_filtering', models.BooleanField(default=True)),
                ('theme', models.CharField(choices=[('dark', 'Dark'), ('light', 'Light')], default='dark', max_length=10)),
                ('default_language', models.CharField(choices=[('python', 'Python'), ('cpp', 'C++'), ('java', 'Java'), ('javascript', 'JavaScript'), ('c', 'C')], default='python', max_length=20)),
                ('font_size', models.PositiveSmallIntegerField(default=14)),
                ('show_line_numbers', models.BooleanField(default=True)),
                ('word_wrap', models.BooleanField(default=True)),
                ('auto_complete', models.BooleanField(default=True)),
                ('auto_save', models.BooleanField(default=False)),
                ('public_profile', models.BooleanField(default=True)),
                ('show_solved_problems', models.BooleanField(default=True)),
                ('show_contest_ranking', models.BooleanField(default=True)),
                ('show_activity', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Settings',
                'verbose_name_plural': 'User Settings',
            },
        ),
    ]
