# Generated by Django 6.0.6 on 2026-07-06 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_bio_user_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRateLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
            },
        ),
        migrations.AddIndex(
            model_name='chatratelimit',
            index=models.Index(fields=['user', 'timestamp'], name='accounts_ch_user_id_1234abc'),
        ),
        migrations.AddIndex(
            model_name='chatratelimit',
            index=models.Index(fields=['ip_address', 'timestamp'], name='accounts_ch_ip_addre_5678def'),
        ),
    ]
