# Generated by Django 6.0.6 on 2026-07-06 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_chatratelimit'),
        ('accounts', '0003_user_bio_user_organization'),
    ]

    operations = [
        # Note: ChatRateLimit is already created by 0002_chatratelimit
        # This merge simply joins the two branches
    ]
