# Generated by Django 6.0.6 on 2026-07-06 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_chatratelimit'),
        ('accounts', '0003_user_bio_user_organization'),
    ]

    operations = [
    ]
