# Generated by Django 4.2.7 on 2026-07-07 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_merge_20260706_2136'),
        ('accounts', '0004_merge_20260706_2211'),
    ]

    operations = [
    ]
