# Generated by Django 5.2.15 on 2026-07-09 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_merge_20260707_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_registered_candidate',
            field=models.BooleanField(default=False),
        ),
    ]
