# Generated by Django 6.0.6 on 2026-07-07 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_rename_source_code_submission_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='time_taken_seconds',
            field=models.PositiveIntegerField(default=0, help_text='Time taken by the candidate in seconds'),
        ),
    ]
