# Generated by Django 4.2.7 on 2026-06-24 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.TextField(blank=True, help_text='Input fed to the program via stdin')),
                ('expected_output', models.TextField(help_text='Exact expected stdout for this input')),
                ('is_sample', models.BooleanField(default=False, help_text='If True, shown to candidates as an example. If False, hidden during grading.')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='questions.question')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
