# Generated by Django 4.2.7 on 2026-06-25 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='input_data',
            field=models.TextField(blank=True, default=''),
        ),
    ]
