# Generated by Django 4.2.7 on 2026-06-24 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestCase',
        ),
    ]
