# Generated by Django 4.2.7 on 2026-06-24 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('quest', 'Quest'), ('study_plan', 'Study Plan'), ('explore', 'Explore')], default='quest', max_length=20)),
                ('icon', models.CharField(default='fas fa-code', max_length=50)),
                ('color', models.CharField(default='#f59e0b', max_length=20)),
                ('levels', models.IntegerField(default=5)),
                ('order', models.IntegerField(default=0)),
            ],
        ),
    ]
